[tool.poetry]
name = 'test-repo'
description = 'testdescription'
version = '1.0.1'

[tool.poetry.dependencies]
python = '^3.6'

[build-system]
requires = ['poetry-core~=1.0']
build-backend = 'poetry.core.masonry.api'